version: '3.3'
services:
    backend:
        container_name: 'backend'
        build: ./
        ports:
            - '8080:8080'
        depends_on:
            - postgres
    postgres:
        image: 'postgres:13'
        container_name: 'postgres'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DATABASE: 'postgres'
